// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class pionex : Exchange
{
    public pionex (object args = null): base(args) {}

    public async Task<object> publicGetCommonSymbols (object parameters = null)
    {
        return await this.callAsync ("publicGetCommonSymbols",parameters);
    }

    public async Task<object> publicGetMarketTrades (object parameters = null)
    {
        return await this.callAsync ("publicGetMarketTrades",parameters);
    }

    public async Task<object> publicGetMarketDepth (object parameters = null)
    {
        return await this.callAsync ("publicGetMarketDepth",parameters);
    }

    public async Task<object> publicGetMarketTickers (object parameters = null)
    {
        return await this.callAsync ("publicGetMarketTickers",parameters);
    }

    public async Task<object> publicGetMarketBookTickers (object parameters = null)
    {
        return await this.callAsync ("publicGetMarketBookTickers",parameters);
    }

    public async Task<object> publicGetMarketKlines (object parameters = null)
    {
        return await this.callAsync ("publicGetMarketKlines",parameters);
    }

    public async Task<object> privateGetAccountBalances (object parameters = null)
    {
        return await this.callAsync ("privateGetAccountBalances",parameters);
    }

    public async Task<object> privateGetTradeOrder (object parameters = null)
    {
        return await this.callAsync ("privateGetTradeOrder",parameters);
    }

    public async Task<object> privateGetTradeOrderByClientOrderId (object parameters = null)
    {
        return await this.callAsync ("privateGetTradeOrderByClientOrderId",parameters);
    }

    public async Task<object> privateGetTradeOpenOrders (object parameters = null)
    {
        return await this.callAsync ("privateGetTradeOpenOrders",parameters);
    }

    public async Task<object> privateGetTradeAllOrders (object parameters = null)
    {
        return await this.callAsync ("privateGetTradeAllOrders",parameters);
    }

    public async Task<object> privateGetTradeFills (object parameters = null)
    {
        return await this.callAsync ("privateGetTradeFills",parameters);
    }

    public async Task<object> privateGetTradeFillsByOrderId (object parameters = null)
    {
        return await this.callAsync ("privateGetTradeFillsByOrderId",parameters);
    }

    public async Task<object> privatePostTradeOrder (object parameters = null)
    {
        return await this.callAsync ("privatePostTradeOrder",parameters);
    }

    public async Task<object> privatePostTradeMassOrder (object parameters = null)
    {
        return await this.callAsync ("privatePostTradeMassOrder",parameters);
    }

    public async Task<object> privateDeleteTradeOrder (object parameters = null)
    {
        return await this.callAsync ("privateDeleteTradeOrder",parameters);
    }

    public async Task<object> privateDeleteTradeAllOrders (object parameters = null)
    {
        return await this.callAsync ("privateDeleteTradeAllOrders",parameters);
    }

}