<?php

namespace ccxt\async;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\async\abstract\pionex as Exchange;
use ccxt\ExchangeError;
use ccxt\ArgumentsRequired;
use React\Async;
use React\Promise\PromiseInterface;

class pionex extends Exchange {

    public function describe() {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'pionex',
            'name' => 'Pionex',
            'countries' => array( 'EU' ),
            'rateLimit' => 100,
            'version' => 'v1',
            'has' => array(
                'CORS' => null,
                'spot' => true,
                'margin' => null,
                'swap' => null,
                'future' => null,
                'option' => null,
                'cancelAllOrders' => true,
                'cancelOrder' => true,
                'cancelOrders' => false,
                'closeAllPositions' => false,
                'closePosition' => false,
                'createDepositAddress' => false,
                'createMarketOrder' => true,
                'createOrder' => true,
                'createOrders' => false, // TODO
                'createPostOnlyOrder' => true,
                'createReduceOnlyOrder' => false,
                'createStopLimitOrder' => false,
                'createStopMarketOrder' => false,
                'createStopOrder' => false,
                'fetchAccounts' => false,
                'fetchBalance' => true,
                'fetchBorrowInterest' => false,
                'fetchBorrowRateHistory' => false,
                'fetchClosedOrders' => false,
                'fetchCrossBorrowRate' => false,
                'fetchCrossBorrowRates' => false,
                'fetchDeposit' => false,
                'fetchDepositAddress' => false,
                'fetchDepositAddresses' => false,
                'fetchDepositAddressesByNetwork' => false,
                'fetchDeposits' => false,
                'fetchDepositsWithdrawals' => false,
                'fetchFundingHistory' => false,
                'fetchFundingRate' => false,
                'fetchFundingRateHistory' => false,
                'fetchFundingRates' => false,
                'fetchIndexOHLCV' => false,
                'fetchIsolatedBorrowRate' => false,
                'fetchIsolatedBorrowRates' => false,
                'fetchLedger' => false,
                'fetchLedgerEntry' => false,
                'fetchLeverageTiers' => false,
                'fetchMarketLeverageTiers' => false,
                'fetchMarkets' => true,
                'fetchMarkOHLCV' => false,
                'fetchMyTrades' => true,
                'fetchOHLCV' => false,
                'fetchOpenInterest' => false,
                'fetchOpenInterestHistory' => false,
                'fetchOpenOrders' => true,
                'fetchOrder' => true,
                'fetchOrderBook' => true,
                'fetchOrderBooks' => true,
                'fetchOrders' => true,
                'fetchOrderTrades' => true,
                'fetchPosition' => false,
                'fetchPositionHistory' => false,
                'fetchPositionMode' => false,
                'fetchPositions' => false,
                'fetchPositionsForSymbol' => false,
                'fetchPositionsHistory' => false,
                'fetchPositionsRisk' => false,
                'fetchPremiumIndexOHLCV' => false,
                'fetchTicker' => true,
                'fetchTickers' => false,
                'fetchTrades' => true,
                'fetchTradingLimits' => false,
                'fetchTransactionFee' => false,
                'fetchTransactionFees' => false,
                'fetchTransactions' => false,
                'fetchTransfers' => false,
                'fetchWithdrawAddresses' => false,
                'fetchWithdrawal' => false,
                'fetchWithdrawals' => false,
                'reduceMargin' => false,
                'setLeverage' => false,
                'setMargin' => false,
                'setMarginMode' => false,
                'setPositionMode' => false,
                'signIn' => false,
                'transfer' => false,
                'withdraw' => false,
            ),
            'timeframes' => array(
                '1m' => '1M',
                '5m' => '5M',
                '15m' => '15M',
                '30m' => '30M',
                '1h' => '60M',
                '4h' => '4H',
                '8h' => '8H',
                '12h' => '12H',
                '1d' => '1D',
            ),
            'urls' => array(
                'api' => array(
                    'public' => 'https://api.pionex.com',
                    'private' => 'https://api.pionex.com',
                ),
                'www' => 'https://www.pionex.com/',
                'doc' => 'https://pionex-doc.gitbook.io/apidocs',
                'fees' => 'https://www.pionex.com/en/fees',
            ),
            'api' => array(
                'public' => array(
                    'get' => array(
                        'common/symbols' => 5,
                        'market/trades' => 1,
                        'market/depth' => 1,
                        'market/tickers' => 1,
                        'market/bookTickers' => 1,
                        'market/klines' => 1,
                    ),
                ),
                'private' => array(
                    'get' => array(
                        'account/balances' => 1,
                        'trade/order' => 1,
                        'trade/orderByClientOrderId' => 1,
                        'trade/openOrders' => 5,
                        'trade/allOrders' => 5,
                        'trade/fills' => 5,
                        'trade/fillsByOrderId' => 5,
                    ),
                    'post' => array(
                        'trade/order' => 1,
                        'trade/massOrder' => 1,
                    ),
                    'delete' => array(
                        'trade/order' => 1,
                        'trade/allOrders' => 1,
                    ),
                ),
            ),
            'fees' => array(
                'trading' => array(
                    'tierBased' => false,
                    'percentage' => true,
                    'taker' => $this->parse_number('0.0005'),
                    'maker' => $this->parse_number('0.0005'),
                ),
            ),
            'precisionMode' => DECIMAL_PLACES,
            'exceptions' => array(
                'APIKEY_LOST' => '\\ccxt\\ArgumentsRequired',
                'SIGNATURE_LOST' => '\\ccxt\\ArgumentsRequired',
                'IP_NOT_WHITELISTED' => '\\ccxt\\InvalidAddress',
                'INVALIE_APIKEY' => '\\ccxt\\AuthenticationError',
                'INVALID_SIGNATURE' => '\\ccxt\\AuthenticationError',
                'APIKEY_EXPIRED' => '\\ccxt\\AuthenticationError',
                'INVALID_TIMESTAMP' => '\\ccxt\\BadRequest',
                'PERMISSION_DENIED' => '\\ccxt\\PermissionDenied',
                'TRADE_INVALID_SYMBOL' => '\\ccxt\\BadSymbol',
                'TRADE_PARAMETER_ERROR' => '\\ccxt\\BadRequest',
                'TRADE_NOT_ENOUGH_MONEY' => '\\ccxt\\InsufficientFunds',
                'TRADE_PRICE_FILTER_DENIED' => '\\ccxt\\BadRequest',
                'TRADE_SIZE_FILTER_DENIED' => '\\ccxt\\BadRequest',
                'TRADE_AMOUNT_FILTER_DENIED' => '\\ccxt\\BadRequest',
                'TRADE_REPEAT_CLIENT_ORDER_ID' => '\\ccxt\\DuplicateOrderId',
                'TRADE_OPEN_ORDER_EXCEED_LIMIT' => '\\ccxt\\DDoSProtection',
                'TRADE_OPERATION_DENIED' => '\\ccxt\\PermissionDenied',
                'TRADE_ORDER_NOT_FOUND' => '\\ccxt\\OrderNotFound',
                'MARKET_INVALID_SYMBOL' => '\\ccxt\\BadSymbol',
            ),
        ));
    }

    public function fetch_markets($params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            /**
             * retrieves $data on all $markets for pionex
             * @see https://pionex-doc.gitbook.io/apidocs/restful/common/market-$data
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array[]} an array of objects representing market $data
             */
            $response = Async\await($this->publicGetCommonSymbols ());
            // {
            //   "data" => {
            //     "symbols":array(
            //       array(
            //         "symbol" => "BTC_USDT",
            //         "type" => "SPOT",
            //         "baseCurrency" => "BTC",
            //         "quoteCurrency" => "USDT",
            //         "basePrecision" => 6,
            //         "quotePrecision" => 2,
            //         "amountPrecision" => 8,
            //         "minAmount" => "10",
            //         "minTradeSize" => "0.000001",
            //         "maxTradeSize" => "1000",
            //         "minTradeDumping" => "0.000001",
            //         "maxTradeDumping" => "100",
            //         "enable" => true,
            //         "buyCeiling" => "1.1",
            //         "sellFloor" => "0.9"
            //       }
            //     )
            //   ),
            //   "result" => true,
            //   "timestamp" => 1566676132311
            // }
            $data = $this->safe_value($response, 'data', array());
            $markets = $this->safe_value($data, 'symbols', array());
            return $this->parse_markets($markets);
        }) ();
    }

    public function parse_market(array $market): array {
        //  {
        //    "symbol" => "BTC_USDT",
        //    "type" => "SPOT",
        //    "baseCurrency" => "BTC",
        //    "quoteCurrency" => "USDT",
        //    "basePrecision" => 6,
        //    "quotePrecision" => 2,
        //    "amountPrecision" => 8,
        //    "minAmount" => "10",
        //    "minTradeSize" => "0.000001",
        //    "maxTradeSize" => "1000",
        //    "minTradeDumping" => "0.000001",
        //    "maxTradeDumping" => "100",
        //    "enable" => true,
        //    "buyCeiling" => "1.1",
        //    "sellFloor" => "0.9"
        //  }
        $baseId = $this->safe_string($market, 'baseCurrency');
        $quoteId = $this->safe_string($market, 'quoteCurrency');
        $type = $this->safe_string_lower($market, 'type');
        $spot = $type === 'spot';
        $id = $baseId . '/' . $quoteId;
        return array(
            'symbol' => $id,
            'id' => $id,
            'spot' => $spot,
            'type' => $type,
            'base' => $baseId,
            'quote' => $quoteId,
            'baseId' => $baseId,
            'quoteId' => $quoteId,
            'active' => $this->safe_bool($market, 'enable'),
            'maker' => 0.0005,
            'taker' => 0.0005,
            'limits' => array(
                'amount' => array(
                    'min' => $this->safe_number($market, 'minTradeSize'),
                    'max' => $this->safe_number($market, 'maxTradeSize'),
                ),
            ),
            'precision' => array(
                'amount' => $this->safe_number($market, 'amountPrecision'),
                'price' => $this->safe_number($market, 'basePrecision'),
                // 'qoute' => $this->safe_number($market, 'quotePrecision'),
            ),
            'info' => $market,
            'contract' => false,
            'contractSize' => null,
            'created' => null,
            'expiry' => null,
            'expiryDatetime' => null,
            'future' => !$spot,
            'inverse' => null,
            'linear' => null,
            'margin' => false,
            'swap' => false,
            'option' => false,
            'optionType' => null,
            'settle' => null,
            'settleId' => null,
            'strike' => null,
        );
    }

    public function fetch_trades(string $symbol, ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $since, $limit, $params) {
            /**
             * get the list of most recent $trades for a particular $symbol
             * @see https://pionex-doc.gitbook.io/apidocs/restful/markets/get-$trades
             * @param {string} $symbol unified $symbol of the $market to fetch $trades for
             * @param {int} [$since] timestamp in ms of the earliest trade to fetch
             * @param {int} [$limit] the maximum amount of $trades to fetch
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {Trade[]} a list of $trades
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $request = array(
                'symbol' => $this->market_api_symbol($market['id']),
            );
            if ($limit !== null) {
                $request['limit'] = min ($limit, 500); // default 100, max 500
            }
            $response = Async\await($this->publicGetMarketTrades ($this->extend($request, $params)));
            // {
            //     "data" => {
            //     "trades" => array(
            //         array(
            //         "symbol" => "BTC_USDT",
            //         "tradeId" => "600848671",
            //         "price" => "7962.62",
            //         "size" => "0.0122",
            //         "side" => "BUY",
            //         "timestamp" => 1566691672311
            //     ),
            //     array(
            //         "symbol" => "BTC_USDT",
            //         "tradeId" => "600848670",
            //         "price" => "7960.12",
            //         "size" => "0.0198",
            //         "side" => "BUY",
            //         "timestamp" => 1566691672311
            //     }
            //     )
            // ),
            //     "result" => true,
            //     "timestamp" => 1566691672311
            // }
            $data = $this->safe_value($response, 'data', array());
            $trades = $this->safe_value($data, 'trades', array());
            return $this->parse_trades($trades, $market, $since, $limit);
        }) ();
    }

    public function parse_trade(array $trade, ?array $market = null): array {
        // publicGetMarketTrades
        // {
        //     "symbol" => "BTC_USDT",
        //     "tradeId" => "600848670",
        //     "price" => "7960.12",
        //     "size" => "0.0198",
        //     "side" => "BUY",
        //     "timestamp" => 1566691672311
        // }
        //
        // privateGetTradeFills
        // array(
        //     "id" => 9876543210,
        //     "orderId" => 22334455,
        //     "symbol" => "BTC_USDT",
        //     "side" => "BUY",
        //     "role" =>  "TAKER",
        //     "price" => "30000.00",
        //     "size" => "0.1000",
        //     "fee" =>  "0.15",
        //     "feeCoin" =>  "USDT",
        //     "timestamp" => 1566676132311
        //   ),
        $timestamp = $this->safe_integer($trade, 'timestamp');
        return $this->safe_trade(array(
            'info' => $trade,
            'id' => $this->safe_string_2($trade, 'tradeId', 'id'),
            'order' => $this->safe_string($trade, 'orderId'),
            'symbol' => str_replace('_', '/', $this->safe_string($trade, 'symbol')),
            'side' => $this->safe_string_lower($trade, 'side'),
            'type' => $this->safe_string_lower($trade, 'type'),
            'takerOrMaker' => $this->safe_string_lower($trade, 'role'),
            'price' => $this->safe_string($trade, 'price'),
            'amount' => $this->safe_string($trade, 'size'),
            'cost' => null,
            'fee' => array(
                'cost' => $this->safe_string($trade, 'fee'),
                'currency' => $this->safe_currency_code($this->safe_string($trade, 'feeCoin')),
                'rate' => null,
            ),
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
        ), $market);
    }

    public function fetch_order_book(string $symbol, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $limit, $params) {
            /**
             * fetches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
             * @see https://pionex-doc.gitbook.io/apidocs/restful/markets/get-depth
             * @param {string} $symbol unified $symbol of the $market to fetch the order book for
             * @param {int} [$limit] the maximum amount of order book entries to return
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} A dictionary of order book structures
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $request = array(
                'symbol' => $this->market_api_symbol($market['id']),
            );
            if ($limit !== null) {
                $request['limit'] = min ($limit, 1000); // default 20, max 1000
            }
            $response = Async\await($this->publicGetMarketDepth ($this->extend($request, $params)));
            // {
            // "data" => array(
            //     "bids" => [
            //         ["29658.37", "0.0123"],
            //         ["29658.35", "1.1234"],
            //         ["29657.99", "2.2345"],
            //         ["29657.56", "6.3456"],
            //         ["29656.13", "8.4567"]
            //     ],
            //     "asks" => [
            //         ["29658.47", "0.0345"],
            //         ["29658.65", "1.0456"],
            //         ["29658.89", "3.5567"],
            //         ["29659.43", "5.2678"],
            //         ["29659.98", "1.9789"]
            //     ]，
            //     "updateTime" => 1566676132311
            // ),
            // "result" => true,
            // "timestamp" => 1566691672311
            // }
            $orderBook = $this->safe_dict($response, 'data');
            return $this->parse_order_book($orderBook, $market['id'], null, 'bids', 'asks');
        }) ();
    }

    public function fetch_ohlcv(string $symbol, $timeframe = '1m', ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $timeframe, $since, $limit, $params) {
            /**
             * fetches historical candlestick $data containing the open, high, low, and close price, and the volume of a $market
             * @see https://pionex-doc.gitbook.io/apidocs/restful/markets/get-$klines
             * @param {string} $symbol unified $symbol of the $market to fetch OHLCV $data for
             * @param {string} $timeframe the length of time each candle represents
             * @param {int} [$since] timestamp in ms of the earliest candle to fetch
             * @param {int} [$limit] the maximum amount of candles to fetch
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {int[][]} A list of candles ordered, open, high, low, close, volume
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $request = array(
                'symbol' => $this->market_api_symbol($market['id']),
            );
            if ($timeframe !== null) {
                $request['interval'] = $this->timeframes[$timeframe];
            }
            if ($limit !== null) {
                $request['limit'] = min ($limit, 500); // default 100, max 500
            }
            if ($since !== null) {
                $duration = $this->parse_timeframe($timeframe);
                $request['endTime'] = min ($this->sum($since, $duration * $limit * 1000), $this->milliseconds());
            }
            $response = Async\await($this->publicGetMarketKlines ($this->extend($request, $params)));
            $data = $this->safe_dict($response, 'data', array());
            $klines = $this->safe_list($data, 'klines', array());
            // {
            // "result" => true,
            // "data" => {
            //     "klines" => array(
            //     array(
            //         "time" => 1691649240000,
            //         "open" => "1851.27",
            //         "close" => "1851.32",
            //         "high" => "1851.32",
            //         "low" => "1851.27",
            //         "volume" => "0.542"
            //     }
            //     )
            // ),
            // "timestamp" => 1691649271544
            // }
            return $this->parse_ohlcvs($klines, $market, $timeframe, $since, $limit);
        }) ();
    }

    public function parse_ohlcv($ohlcv, ?array $market = null): array {
        // {
        //     "time" => 1691649240000,
        //     "open" => "1851.27",
        //     "close" => "1851.32",
        //     "high" => "1851.32",
        //     "low" => "1851.27",
        //     "volume" => "0.542"
        // }
        return array(
            $this->safe_integer($ohlcv, 'time'),  // timestamp
            $this->safe_number($ohlcv, 'open'),  // open
            $this->safe_number($ohlcv, 'high'),  // high
            $this->safe_number($ohlcv, 'low'),  // low
            $this->safe_number($ohlcv, 'close'),  // close
            $this->safe_number($ohlcv, 'volume'),  // volume
        );
    }

    public function fetch_tickers(?array $symbols = null, $params = { }): PromiseInterface {
        return Async\async(function () use ($symbols, $params) {
            /**
             * fetches price $tickers for multiple markets, statistical information calculated over the past 24 hours for each market
             * @see https://pionex-doc.gitbook.io/apidocs/restful/markets/get-24hr-$ticker
             * @see https://pionex-doc.gitbook.io/apidocs/restful/markets/get-book-$ticker
             * @param {string[]|null} $symbols unified $symbols of the markets to fetch the $ticker for, all market $tickers are returned if not assigned
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} a dictionary of $ticker structures]
             */
            Async\await($this->load_markets());
            if ($params['type'] === null) {
                $params['type'] = 'SPOT';
            }
            $request = $params;
            $response = Async\await($this->publicGetMarketTickers ($request));
            // {
            // "data" => {
            //     "tickers" => array(
            //     array(
            //         "symbol" => "BTC_USDT",
            //         "time" => 1545291675000,
            //         "open" => "7962.62",
            //         "close" => "7952.32",
            //         "high" => "7971.61",
            //         "low" => "7950.29",
            //         "volume" => "1.537",
            //         "amount" => "12032.56",
            //         "count" => 271585
            //     ),
            //     array(
            //         "symbol" => "ETH_USDT",
            //         "time" => 1545291675000,
            //         "open" => "1963.62",
            //         "close" => "1852.22",
            //         "high" => "1971.11",
            //         "low" => "1850.23",
            //         "volume" => "100.532",
            //         "amount" => "112012.51",
            //         "count" => 432211
            //     }
            //     )
            // ),
            // "result" => true,
            // "timestamp" => 1566691672311
            // }
            $response2 = Async\await($this->publicGetMarketBookTickers ($request));
            // {
            // "data" => array(
            //     "tickers" => array(
            //     )
            // ),
            // "result" => true,
            // "timestamp" => 1566691672311
            // }
            $data = $this->safe_dict($response, 'data', array());
            $data2 = $this->safe_dict($response2, 'data', array());
            $tickers = $this->safe_list($data, 'tickers', array());
            $tickers2 = $this->safe_list($data2, 'tickers', array());
            $symbolsChanged = array();
            if ($symbols === null) {
                $symbols = array();
                for ($i = 0; $i < count($this->symbols); $i++) {
                    $symbol = $this->symbols[$i];
                    $symbols[$i] = str_replace('/', '_', $symbol);
                    $symbolsChanged[] = $this->market_api_symbol($symbols[$i]);
                }
            }
            $tickers = $this->filter_by_array($tickers, 'symbol', $symbolsChanged);
            $tickers2 = $this->filter_by_array($tickers2, 'symbol', $symbolsChanged);
            $tickersFinal = array();
            $unmatchedTickers = array();
            for ($i = 0; $i < count($tickers); $i++) {
                $ticker = $tickers[$i];
                $ticker['symbol'] = str_replace('_', '/', $ticker['symbol']);
                for ($j = 0; $j < count($tickers2); $j++) {
                    $ticker2 = $tickers2[$j];
                    $ticker2['symbol'] = str_replace('_', '/', $ticker2['symbol']);
                    if ($ticker2['symbol'] === $ticker['symbol']) {
                        $tickersFinal[] = $this->extend($ticker, $ticker2);
                    } else {
                        $unmatchedTickers[$i] = $ticker;
                        $tickersFinal[] = $ticker2;
                    }
                }
            }
            for ($i = 0; $i < count($unmatchedTickers); $i++) {
                $ticker = $unmatchedTickers[$i];
                $tickersFinal[] = $ticker;
            }
            $tickersFinal = $this->filter_by_array($tickersFinal, 'symbol', $this->symbols);
            return $this->parse_tickers($tickersFinal, $this->symbols);
        }) ();
    }

    public function fetch_ticker(string $symbol, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $params) {
            /**
             * fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific $market
             * @see https://pionex-doc.gitbook.io/apidocs/restful/markets/get-24hr-ticker
             * @see https://pionex-doc.gitbook.io/apidocs/restful/markets/get-book-ticker
             * @param {string} $symbol unified $symbol of the $market to fetch the ticker for
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} a ~@link https://docs.ccxt.com/#/?id=ticker-structure ticker structure~
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $request = array(
                'symbol' => $this->market_api_symbol($market['id']),
                'type' => $this->safe_string_upper($market, 'type'),
            );
            $response = Async\await($this->publicGetMarketTickers ($this->extend($request, $params)));
            // {
            // "data" => {
            //     "tickers" => array(
            //     array(
            //         "symbol" => "BTC_USDT",
            //         "time" => 1545291675000,
            //         "open" => "7962.62",
            //         "close" => "7952.32",
            //         "high" => "7971.61",
            //         "low" => "7950.29",
            //         "volume" => "1.537",
            //         "amount" => "12032.56",
            //         "count" => 271585
            //     ),
            //     array(
            //         "symbol" => "ETH_USDT",
            //         "time" => 1545291675000,
            //         "open" => "1963.62",
            //         "close" => "1852.22",
            //         "high" => "1971.11",
            //         "low" => "1850.23",
            //         "volume" => "100.532",
            //         "amount" => "112012.51",
            //         "count" => 432211
            //     }
            //     )
            // ),
            // "result" => true,
            // "timestamp" => 1566691672311
            // }
            $response2 = Async\await($this->publicGetMarketBookTickers ($this->extend($request, $params)));
            // {
            // "data" => array(
            //     "tickers" => array(
            //     )
            // ),
            // "result" => true,
            // "timestamp" => 1566691672311
            // }
            $data = $this->safe_dict($response, 'data', array());
            $data2 = $this->safe_dict($response2, 'data', array());
            $tickers = $this->safe_list($data, 'tickers', array());
            $tickers2 = $this->safe_list($data2, 'tickers', array());
            return $this->parse_ticker($this->extend($tickers[0], $tickers2[0]), $market);
        }) ();
    }

    public function parse_ticker(array $ticker, ?array $market = null): array {
        // {
        //     "symbol" => "ETH_USDT",
        //     "time" => 1545291675000,
        //     "open" => "1963.62",
        //     "close" => "1852.22",
        //     "high" => "1971.11",
        //     "low" => "1850.23",
        //     "volume" => "100.532",
        //     "amount" => "112012.51",
        //     "count" => 432211
        // }
        $timestamp = $this->safe_number($ticker, 'time');
        return $this->safe_ticker(array(
            'symbol' => str_replace('_', '/', $this->safe_string($ticker, 'symbol')),
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'high' => $this->safe_number($ticker, 'high'),
            'low' => $this->safe_number($ticker, 'low'),
            'open' => $this->safe_number($ticker, 'open'),
            'close' => $this->safe_number($ticker, 'close'),
            'baseVolume' => $this->safe_number($ticker, 'volume'),
            'info' => $ticker,
            'bid' => $this->safe_number($ticker, 'bidPrice'),
            'bidVolume' => $this->safe_number($ticker, 'bidSize'),
            'ask' => $this->safe_number($ticker, 'askPrice'),
            'askVolume' => $this->safe_number($ticker, 'askSize'),
            'vwap' => null,
            'last' => $this->safe_string($ticker, 'last_price'),
            'previousClose' => null,
            'change' => null,
            'percentage' => null,
            'average' => null,
            'quoteVolume' => $this->safe_string($ticker, 'quote_volume'),
        ), $market);
    }

    public function fetch_balance($params = array ()): PromiseInterface {
        return Async\async(function () use ($params) {
            /**
             * query for balance and get the amount of funds available for trading or funds locked in orders
             * @see https://pionex-doc.gitbook.io/apidocs/restful/account/get-balance
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} a balance structure
             */
            Async\await($this->load_markets());
            $response = Async\await($this->privateGetAccountBalances ($this->extend($params)));
            // {
            // "data" => {
            //     "balances" => array(
            //     array(
            //         "coin" => "BTC",
            //         "free" => "0.9000000",
            //         "frozen" => "0.00000000"
            //     ),
            //     array(
            //         "coin" => "USDT",
            //         "free" => "100.00000000",
            //         "frozen" => "900.00000000"
            //     }
            //     )
            // ),
            // "result" => true,
            // "timestamp" => 1566691672311
            // }
            return $this->parse_balance($response);
        }) ();
    }

    public function parse_balance($response): array {
        // {
        // "data" => {
        //     "balances" => array(
        //     array(
        //         "coin" => "BTC",
        //         "free" => "0.9000000",
        //         "frozen" => "0.00000000"
        //     ),
        //     array(
        //         "coin" => "USDT",
        //         "free" => "100.00000000",
        //         "frozen" => "900.00000000"
        //     }
        //     )
        // ),
        // "result" => true,
        // "timestamp" => 1566691672311
        // }
        $data = $this->safe_dict($response, 'data', array());
        $balances = $this->safe_list($data, 'balances', array());
        $timestamp = $this->safe_string($response, 'timestamp');
        $result = array(
            'info' => $balances,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
        );
        for ($i = 0; $i < count($response); $i++) {
            $balance = $balances[$i];
            $currencyId = $this->safe_string($balance, 'coin');
            $code = $this->safe_currency_code($currencyId);
            $account = $this->account();
            $account['free'] = $this->safe_string($balance, 'free');
            $frozen = $this->safe_number($balance, 'frozen');
            $account['total'] = (+$account['free'] . (string) $frozen);
            $result[$code] = $account;
        }
        return $this->safe_balance($result);
    }

    public function fetch_orders(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $since, $limit, $params) {
            /**
             * fetches information on multiple $orders made by the user
             * @see https://pionex-doc.gitbook.io/apidocs/restful/orders/get-all-$orders
             * @param {string} $symbol unified $market $symbol of the $market $orders were made in
             * @param {int} [$since] the earliest time in ms to fetch $orders for
             * @param {int} [$limit] the maximum number of order structures to retrieve
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {Order[]} a list of ~@link https://docs.ccxt.com/#/?id=order-structure order structures~
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $request = array(
                'symbol' => $this->market_api_symbol($market['id']),
            );
            if ($limit === null) {
                $limit = 50;  // max = 200
            } else {
                $limit = min (200, $limit);
            }
            $response = $this->privateGetTradeAllOrders ($this->extend($request, $params));
            // {
            // "data" => {
            //    "orders":array(
            //    array(
            //        // "orderId" => 1234567890,
            //        // "symbol" => "BTC_USDT",
            //        // "type" => "LIMIT",
            //        // "side" => "SELL",
            //        // "price" => "30000.00",
            //        // "size" => "0.1000",
            //        // "filledSize" => "0.0500",
            //        // "filledAmount" => "1500.00",
            //        // "fee" =>  "0.15",
            //        // "feeCoin" =>  "USDT",
            //        // "status" => "OPEN",
            //        // "IOC" => false,
            //        // "clientOrderId" =>  "9e3d93d6-e9a4-465a-a39c-2e48568fe194",
            //        // "source" => "API",
            //        // "createTime" => 1566676132311,
            //        // "updateTime" => 1566676132311
            //     }
            //    )
            // ),
            // "result" => true,
            // "timestamp" => 1566691672311
            // }
            $data = $this->safe_dict($response, 'data', array());
            $orders = $this->safe_list($data, 'orders', array());
            return $this->parse_orders($orders, $market, $since, $limit);
        }) ();
    }

    public function fetch_open_orders(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()): PromiseInterface {
        return Async\async(function () use ($symbol, $since, $limit, $params) {
            /**
             * fetch all unfilled currently open $orders
             * @see https://github.com/ace-exchange/ace-official-api-docs/blob/master/api_v2.md#open-api---order-list
             * @param {string} $symbol unified $market $symbol of the $market $orders were made in
             * @param {int} [$since] the earliest time in ms to fetch $orders for
             * @param {int} [$limit] the maximum number of order structures to retrieve
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {Order[]} a list of ~@link https://docs.ccxt.com/#/?id=order-structure order structures~
             */
            if ($symbol === null) {
                throw new ArgumentsRequired($this->id . ' fetchOpenOrders() requires a $symbol argument');
            }
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $request = array(
                'symbol' => $this->market_api_symbol($market['id']),
            );
            if ($limit === null) {
                $limit = 50;  // max = 200
            } else {
                $limit = min (200, $limit);
            }
            $response = Async\await($this->privateGetTradeOpenOrders ($this->extend($request, $params)));
            // {
            //     "data" => {
            //       "orders":array(
            //         array(
            //           "orderId" => 1234567890,
            //           "symbol" => "BTC_USDT",
            //           "type" => "LIMIT",
            //           "side" => "SELL",
            //           "price" => "30000.00",
            //           "size" => "0.1000",
            //           "filledSize" => "0.0500",
            //           "filledAmount" => "1500.00",
            //           "fee" =>  "0.15",
            //           "feeCoin" =>  "USDT",
            //           "status" => "OPEN",
            //           "IOC" => false,
            //           "clientOrderId" =>  "9e3d93d6-e9a4-465a-a39c-2e48568fe194",
            //           "source" => "API",
            //           "createTime" => 1566676132311,
            //           "updateTime" => 1566676132311
            //         }
            //       )
            //     ),
            //     "result" => true,
            //     "timestamp" => 1566676132311
            //   }
            $data = $this->safe_dict($response, 'data', array());
            $orders = $this->safe_list($data, 'orders', array());
            return $this->parse_orders($orders, $market, $since, $limit);
        }) ();
    }

    public function fetch_order(string $id, ?string $symbol = null, $params = array ()) {
        return Async\async(function () use ($id, $symbol, $params) {
            /**
             * fetches information on an order made by the user
             * @see https://pionex-doc.gitbook.io/apidocs/restful/orders/get-order
             * @param {string} $id the order $id
             * @param {string} $symbol unified $symbol of the market the order was made in
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} An ~@link https://docs.ccxt.com/#/?$id=order-structure order structure~
             */
            Async\await($this->load_markets());
            $clientOrderId = $this->safe_value_2($params, 'client_order_id', 'clientOrderId');
            $request = array();
            if ($clientOrderId !== null) {
                $request['clientOrderId'] = $clientOrderId;
                $params = $this->omit($params, array( 'client_order_id', 'clientOrderId' ));
                $response = $this->privateGetTradeOrderByClientOrderId ($this->extend($request, $params));
            } else {
                $request['orderId'] = $id;
                $response = $this->privateGetTradeOrder ($this->extend($request, $params));
            }
            // {
            // "data" => array(
            //     "orderId" => 1234567890,
            //     "symbol" => "BTC_USDT",
            //     "type" => "LIMIT",
            //     "side" => "SELL",
            //     "price" => "30000.00",
            //     "size" => "0.1000",
            //     "filledSize" => "0.0500",
            //     "filledAmount" => "1500.00",
            //     "fee" =>  "0.15",
            //     "feeCoin" =>  "USDT",
            //     "status" => "OPEN",
            //     "IOC" =>  false,
            //     "clientOrderId" =>  "9e3d93d6-e9a4-465a-a39c-2e48568fe194",
            //     "source" => "API",
            //     "createTime" => 1566676132311,
            //     "updateTime" => 1566676132311
            // ),
            // "result" => true,
            // "timestamp" => 1566691672311
            // }
            $data = $this->safe_dict($response, 'data', array());
            return $this->parse_order($data, null);
        }) ();
    }

    public function parse_order(array $order, ?array $market = null): array {
        // {
        //     "orderId" => 1234567890,
        //     "symbol" => "BTC_USDT",
        //     "type" => "LIMIT",
        //     "side" => "SELL",
        //     "price" => "30000.00",
        //     "size" => "0.1000",
        //     "filledSize" => "0.0500",
        //     "filledAmount" => "1500.00",
        //     "fee" =>  "0.15",
        //     "feeCoin" =>  "USDT",
        //     "status" => "OPEN",
        //     "IOC" =>  false,
        //     "clientOrderId" =>  "9e3d93d6-e9a4-465a-a39c-2e48568fe194",
        //     "source" => "API",
        //     "createTime" => 1566676132311,
        //     "updateTime" => 1566676132311
        // }
        $timestamp = $this->safe_number($order, 'createTime');
        $size = $this->safe_number($order, 'size');
        $filledSize = $this->safe_number($order, 'filledSize');
        $side = $this->safe_string_lower($order, 'side');
        $remaining = $size - $filledSize;
        $average = 0;
        if ($filledSize) {
            $average = $this->safe_number($order, 'filledAmount') / $filledSize;
        }
        if ($side === 'buy') {
            $remaining = $filledSize - $size;
        }
        return $this->safe_order(array(
            'id' => $this->safe_string($order, 'orderId'),
            'clientOrderId' => $this->safe_string($order, 'clientOrderId'),
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'lastTradeTimestamp' => $this->safe_number($order, 'updateTime'),
            'status' => $this->safe_string_lower($order, 'status'),
            'symbol' => str_replace('_', '/', $this->safe_string($order, 'symbol')),
            'type' => $this->safe_string_lower($order, 'type'),
            'timeInForce' => null,
            'postOnly' => $this->safe_bool($order, 'IOC'),
            'side' => $side,
            'price' => $this->safe_number($order, 'price'),
            'stopPrice' => null,
            'triggerPrice' => $this->safe_number($order, 'price'),
            'amount' => $size,
            'filled' => $filledSize,
            'remaining' => $remaining,
            'cost' => $this->safe_number($order, 'fee'),
            'trades' => null,
            'average' => $average,
            'fee' => array(
                'currency' => $this->safe_string($order, 'feeCoin'),
                'cost' => $this->safe_string($order, 'fee'),
            ),
            'info' => $order,
        ), $market);
    }

    public function fetch_my_trades(?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()) {
        return Async\async(function () use ($symbol, $since, $limit, $params) {
            /**
             * fetch all trades made by the user
             * @see https://pionex-doc.gitbook.io/apidocs/restful/orders/get-$fills
             * @param {string} $symbol unified $symbol of the $market to fetch trades for
             * @param {int} [$since] timestamp in ms of the earliest trade to fetch
             * @param {int} [$limit] the maximum amount of trades to fetch
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {Trade[]} a list of ~@link https://docs.ccxt.com/#/?id=public-trades trade structures~
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $request = array(
                'symbol' => $this->market_api_symbol($market['id']),
            );
            $response = $this->privateGetTradeFills ($this->extend($request, $params));
            // {
            // "data" => {
            //     "fills":array(
            //     array(
            //         "id" => 9876543210,
            //         "orderId" => 123456789,
            //         "symbol" => "BTC_USDT",
            //         "side" => "SELL",
            //         "role" =>  "TAKER",
            //         "price" => "30000.00",
            //         "size" => "0.1000",
            //         "fee" =>  "0.15",
            //         "feeCoin" =>  "USDT",
            //         "timestamp" => 1566676132311
            //     ),
            //     array(
            //         "id" => 9876543200,
            //         "orderId" => 123456789,
            //         "symbol" => "BTC_USDT",
            //         "side" => "SELL",
            //         "role" =>  "TAKER",
            //         "price" => "29000.00",
            //         "size" => "0.1200",
            //         "fee" =>  "0.145",
            //         "feeCoin" =>  "USDT",
            //         "timestamp" => 1566676132310
            //     }
            //     )
            // ),
            // "result" => true,
            // "timestamp" => 1566691672311
            // }
            $data = $this->safe_dict($response, 'data', array());
            $fills = $this->safe_list($data, 'fills', array());
            return $this->parse_trades($fills, $market, $since, $limit);
        }) ();
    }

    public function fetch_order_trades(string $id, ?string $symbol = null, ?int $since = null, ?int $limit = null, $params = array ()) {
        return Async\async(function () use ($id, $symbol, $since, $limit, $params) {
            /**
             * fetch all the trades made from a single order
             * @see https://pionex-doc.gitbook.io/apidocs/restful/orders/get-$fills-by-order-$id
             * @param {string} $id order $id
             * @param {string} $symbol unified $market $symbol
             * @param {int} [$since] the earliest time in ms to fetch trades for
             * @param {int} [$limit] the maximum number of trades to retrieve
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array[]} a list of ~@link https://docs.ccxt.com/#/?$id=trade-structure trade structures~
             */
            Async\await($this->load_markets());
            $market = $this->safe_market($symbol);
            $request = array(
                'orderId' => $id,
            );
            $response = Async\await($this->privateGetTradeFillsByOrderId ($this->extend($request, $params)));
            // {
            //     "data" => {
            //       "fills":array(
            //         array(
            //           "id" => 9876543210,
            //           "orderId" => 22334455,
            //           "symbol" => "BTC_USDT",
            //           "side" => "BUY",
            //           "role" =>  "TAKER",
            //           "price" => "30000.00",
            //           "size" => "0.1000",
            //           "fee" =>  "0.15",
            //           "feeCoin" =>  "USDT",
            //           "timestamp" => 1566676132311
            //         ),
            //         array(
            //           "id" => 9876543200,
            //           "orderId" => 22334455,
            //           "symbol" => "BTC_USDT",
            //           "side" => "BUY",
            //           "role" =>  "TAKER",
            //           "price" => "29000.00",
            //           "size" => "0.1200",
            //           "fee" =>  "0.145",
            //           "feeCoin" =>  "USDT",
            //           "timestamp" => 1566676132310
            //         }
            //       )
            //     ),
            //     "result" => true,
            //     "timestamp" => 1566691672311
            //   }
            $data = $this->safe_dict($response, 'data');
            $fills = $this->safe_list($data, 'fills', array());
            return $this->parse_trades($fills, $market, $since, $limit);
        }) ();
    }

    public function cancel_order(string $id, ?string $symbol = null, $params = array ()) {
        return Async\async(function () use ($id, $symbol, $params) {
            /**
             * cancels an open $order
             * @see https://pionex-doc.gitbook.io/apidocs/restful/orders/cancel-$order
             * @param {string} $id $order $id
             * @param {string} $symbol unified $symbol of the $market the $order was made in
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} An ~@link https://docs.ccxt.com/#/?$id=$order-structure $order structure~
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $request = array(
                'symbol' => $this->market_api_symbol($market['id']),
                'orderId' => $id,
            );
            $this->privateDeleteTradeOrder ($this->extend($request, $params));
            // {
            // "result" => true,
            // "timestamp" => 1566691672311
            // }
            $order = $this->safe_order(array( 'id' => $id, 'symbol' => $market['id'], 'info' => array()), $market);
            return $order;
        }) ();
    }

    public function cancel_all_orders(?string $symbol = null, $params = array ()) {
        return Async\async(function () use ($symbol, $params) {
            /**
             * cancel all open orders in a $market
             * @see https://pionex-doc.gitbook.io/apidocs/restful/orders/cancel-all-orders
             * @param {string} $symbol unified $market $symbol of the $market to cancel orders in
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array[]} a list of ~@link https://docs.ccxt.com/#/?id=$order-structure $order structures~
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $request = array(
                'symbol' => $this->market_api_symbol($market['id']),
            );
            $this->privateDeleteTradeAllOrders ($this->extend($request, $params));
            //  {
            //  "result" => true,
            //  "timestamp" => 1566691672311
            //  }
            $order = $this->safe_order(array( 'symbol' => $market['id'], 'info' => array()), $market);
            return array( $order );
        }) ();
    }

    public function create_order(string $symbol, string $type, string $side, float $amount, ?float $price = null, $params = array ()) {
        return Async\async(function () use ($symbol, $type, $side, $amount, $price, $params) {
            /**
             * create a trade order
             * @see https://pionex-doc.gitbook.io/apidocs/restful/orders/new-order
             * @param {string} $symbol unified $symbol of the $market to create an order in
             * @param {string} $type 'market' or 'limit'
             * @param {string} $side 'buy' or 'sell'
             * @param {float} $amount how much of currency you want to trade in units of base currency
             * @param {float} [$price] the $price at which the order is to be fulfilled, in units of the quote currency, ignored in $market orders
             * @param {array} [$params] extra parameters specific to the exchange API endpoint
             * @return {array} an ~@link https://docs.ccxt.com/#/?id=order-structure order structure~
             */
            Async\await($this->load_markets());
            $market = $this->market($symbol);
            $clientOrderId = $this->safe_string_2($params, 'client_order_id', 'clientOrderId', $this->uuid());
            $request = array(
                'symbol' => $this->market_api_symbol($market['id']),
                'side' => strtoupper($side),
                'type' => strtoupper($type),
                'amount' => $this->amount_to_precision($symbol, $amount),
                'size' => $this->amount_to_precision($symbol, $amount),
                'IOC' => $this->safe_bool($params, 'postOnly', false),
                'clientOrderId' => $clientOrderId,
            );
            if ($price) {
                $request['price'] = $price;
            }
            $response = $this->privatePostTradeOrder ($this->extend($request, $params));
            // {
            //     "data" => array(
            //         "orderId" => 1234567890,
            //         "clientOrderId" =>  "9e3d93d6-e9a4-465a-a39c-2e48568fe194"
            //     ),
            //     "result" => true,
            //     "timestamp" => 1566691672311
            // }
            $data = $this->safe_dict($response, 'data', array());
            $request['orderId'] = $data['orderId'];
            return $this->parse_order($request, $market);
        }) ();
    }

    public function create_orders(array $orders, $params = array ()) {
        return Async\async(function () use ($orders, $params) {
            /**
             * create a list of trade $orders
             * @see https://pionex-doc.gitbook.io/apidocs/restful/orders/new-multiple-order
             * @param {Array} $orders list of $orders to create, each object should contain the parameters required by createOrder, namely $symbol, $type, $side, $amount, $price and $params
             * @param {array} [$params]  extra parameters specific to the exchange API endpoint
             * @return {array} an ~@link https://docs.ccxt.com/#/?id=order-structure order structure~
             */
            Async\await($this->load_markets());
            $ordersRequests = array();
            for ($i = 0; $i < count($orders); $i++) {
                $rawOrder = $orders[$i];
                $symbol = $this->safe_string($rawOrder, 'symbol');
                $type = $this->safe_string($rawOrder, 'type');
                $side = $this->safe_string_upper($rawOrder, 'side');
                $amount = $this->safe_number($rawOrder, 'amount');
                $price = $this->safe_number($rawOrder, 'price');
                $orderParams = $this->safe_dict($rawOrder, 'params', array());
                $orderRequest = $this->create_order_request($symbol, $type, $side, $amount, $price, $orderParams);
                $ordersRequests[] = $orderRequest;
            }
            $firstOrder = $ordersRequests[0];
            $firstSymbol = $this->safe_string($firstOrder, 'symbol');
            $request = array(
                'symbol' => $firstSymbol,
                'orders' => $ordersRequests,
            );
            $response = $this->privatePostTradeMassOrder ($this->extend($request, $params));
            $data = $this->safe_dict($response, 'data', array());
            $orderIds = $this->safe_list($data, 'orderIds', array());
            $responseOrders = array();
            for ($i = 0; $i < count($orderIds); $i++) {
                $responseOrder = $this->safe_dict($orderIds, $i, array());
                $orderRequests = $this->safe_dict($ordersRequests, $i, array());
                $orderRequests['orderId'] = $responseOrder['orderId'];
                $responseOrders[] = $orderRequests;
            }
            return $this->parse_orders($responseOrders);
        }) ();
    }

    public function sign($path, $api = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $endpointPath = '/api/v1/' . $this->implode_params($path, $params);
        $url = $this->urls['api'][$api] . $endpointPath;
        $params = $this->omit($params, $this->extract_params($path));
        if ($params && $method === 'GET' && $api !== 'private') {
            $url .= '?' . $this->urlencode($params);
        }
        if ($api === 'private') {
            if ($params && ($method === 'POST' || $method === 'DELETE')) {
                $body = $this->json($params);
            }
            $params['timestamp'] = $this->milliseconds();
            $url .= '?' . $this->urlencode($params);
            $sortedParams = $this->keysort($params);
            $structedPath = $method . $endpointPath . '?' . $this->urlencode($sortedParams);
            if ($body) {
                $structedPath = $structedPath . $body;
            }
            $signature = $this->hmac($this->encode($structedPath), $this->encode($this->secret), 'sha256');
            $headers = array(
                'Content-Type' => 'application/json',
                'PIONEX-KEY' => $this->apiKey,
                'PIONEX-SIGNATURE' => $signature,
            );
        }
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }

    public function handle_errors(int $code, string $reason, string $url, string $method, array $headers, string $body, $response, $requestHeaders, $requestBody) {
        if ($response === null) {
            return null; // fallback to the default error handler
        }
        if (!$this->safe_bool($response, 'result', false)) {
            $feedback = $this->id . ' ' . $this->json($response);
            $this->throw_exactly_matched_exception($this->exceptions, $this->safe_string($response, 'code'), $feedback);
            throw new ExchangeError($feedback);
        }
        return null;
    }

    public function create_order_request(?string $symbol, string $type, string $side, ?float $amount, ?float $price = null, $params = array ()) {
        $market = $this->market($symbol);
        $clientOrderId = $this->safe_string_2($params, 'client_order_id', 'clientOrderId', $this->uuid());
        $params = $this->omit($params, array( 'client_order_id', 'clientOrderId' ));
        $request = array(
            'clientOrderId' => $clientOrderId,
            'side' => $side,
            'symbol' => $this->market_api_symbol($market['id']),
            'type' => 'LIMIT',  // Only support LIMIT.
            'size' => $this->amount_to_precision($symbol, $amount),
            'price' => $price,
        );
        return $this->extend($request, $params);
    }

    public function market_api_symbol(?string $symbol) {
        return str_replace('/', '_', $symbol);
    }
}
