<?php

namespace ccxt\async\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class pionex extends \ccxt\async\Exchange {
    public function public_get_common_symbols($params = array()) {
        return $this->request('common/symbols', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    public function public_get_market_trades($params = array()) {
        return $this->request('market/trades', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_market_depth($params = array()) {
        return $this->request('market/depth', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_market_tickers($params = array()) {
        return $this->request('market/tickers', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_market_booktickers($params = array()) {
        return $this->request('market/bookTickers', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function public_get_market_klines($params = array()) {
        return $this->request('market/klines', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_account_balances($params = array()) {
        return $this->request('account/balances', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_trade_order($params = array()) {
        return $this->request('trade/order', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_trade_orderbyclientorderid($params = array()) {
        return $this->request('trade/orderByClientOrderId', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function private_get_trade_openorders($params = array()) {
        return $this->request('trade/openOrders', 'private', 'GET', $params, null, null, array("cost" => 5));
    }
    public function private_get_trade_allorders($params = array()) {
        return $this->request('trade/allOrders', 'private', 'GET', $params, null, null, array("cost" => 5));
    }
    public function private_get_trade_fills($params = array()) {
        return $this->request('trade/fills', 'private', 'GET', $params, null, null, array("cost" => 5));
    }
    public function private_get_trade_fillsbyorderid($params = array()) {
        return $this->request('trade/fillsByOrderId', 'private', 'GET', $params, null, null, array("cost" => 5));
    }
    public function private_post_trade_order($params = array()) {
        return $this->request('trade/order', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function private_post_trade_massorder($params = array()) {
        return $this->request('trade/massOrder', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function private_delete_trade_order($params = array()) {
        return $this->request('trade/order', 'private', 'DELETE', $params, null, null, array("cost" => 1));
    }
    public function private_delete_trade_allorders($params = array()) {
        return $this->request('trade/allOrders', 'private', 'DELETE', $params, null, null, array("cost" => 1));
    }
    public function publicGetCommonSymbols($params = array()) {
        return $this->request('common/symbols', 'public', 'GET', $params, null, null, array("cost" => 5));
    }
    public function publicGetMarketTrades($params = array()) {
        return $this->request('market/trades', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetMarketDepth($params = array()) {
        return $this->request('market/depth', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetMarketTickers($params = array()) {
        return $this->request('market/tickers', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetMarketBookTickers($params = array()) {
        return $this->request('market/bookTickers', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function publicGetMarketKlines($params = array()) {
        return $this->request('market/klines', 'public', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetAccountBalances($params = array()) {
        return $this->request('account/balances', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetTradeOrder($params = array()) {
        return $this->request('trade/order', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetTradeOrderByClientOrderId($params = array()) {
        return $this->request('trade/orderByClientOrderId', 'private', 'GET', $params, null, null, array("cost" => 1));
    }
    public function privateGetTradeOpenOrders($params = array()) {
        return $this->request('trade/openOrders', 'private', 'GET', $params, null, null, array("cost" => 5));
    }
    public function privateGetTradeAllOrders($params = array()) {
        return $this->request('trade/allOrders', 'private', 'GET', $params, null, null, array("cost" => 5));
    }
    public function privateGetTradeFills($params = array()) {
        return $this->request('trade/fills', 'private', 'GET', $params, null, null, array("cost" => 5));
    }
    public function privateGetTradeFillsByOrderId($params = array()) {
        return $this->request('trade/fillsByOrderId', 'private', 'GET', $params, null, null, array("cost" => 5));
    }
    public function privatePostTradeOrder($params = array()) {
        return $this->request('trade/order', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function privatePostTradeMassOrder($params = array()) {
        return $this->request('trade/massOrder', 'private', 'POST', $params, null, null, array("cost" => 1));
    }
    public function privateDeleteTradeOrder($params = array()) {
        return $this->request('trade/order', 'private', 'DELETE', $params, null, null, array("cost" => 1));
    }
    public function privateDeleteTradeAllOrders($params = array()) {
        return $this->request('trade/allOrders', 'private', 'DELETE', $params, null, null, array("cost" => 1));
    }
}
